In [71]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [72]:
df = pd.read_csv("HousePricePrediction.csv")

In [73]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [75]:
df.tail()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [76]:
df2 = df.dropna()

In [77]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   object
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   object
 5   BldgType      1460 non-null   object
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   object
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 159.7+ KB

In [78]:
df2['MSZoning'].unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

In [79]:
df2['LotConfig'].unique()

array(['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3'], dtype=object)

In [80]:
df2['BldgType'].unique()

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

In [81]:
X = df2[['MSSubClass', 'LotArea', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF2', 'TotalBsmtSF']]

In [82]:
y = df2['SalePrice']

In [83]:
import numpy as np
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [85]:
X_train

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
615,85,8800,7,1963,1963,0.0,936.0
613,20,8402,5,2007,2007,0.0,1120.0
1303,20,8688,5,2005,2005,0.0,1616.0
486,20,10289,7,1965,1965,0.0,1073.0
561,20,10010,5,1974,1975,123.0,1389.0
...,...,...,...,...,...,...,...
1095,20,9317,5,2006,2006,0.0,1314.0
1130,50,7804,3,1928,1950,0.0,1122.0
1294,20,8172,7,1955,1990,0.0,864.0
860,50,7642,8,1918,1998,0.0,912.0
1126,120,3684,5,2007,2007,0.0,1373.0

In [86]:
X_test

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
892,20,8414,8,1963,2003,0.0,1059.0
1105,60,12256,5,1994,1995,0.0,1463.0
413,30,8960,6,1927,1950,0.0,1008.0
522,50,5000,7,1947,1950,0.0,1004.0
1036,20,12898,5,2007,2008,0.0,1620.0
...,...,...,...,...,...,...,...
1010,50,21286,5,1948,1950,0.0,720.0
390,50,8405,8,1900,1950,391.0,861.0
1409,60,20544,6,1986,1991,0.0,791.0
847,20,15523,6,1972,1972,0.0,864.0
1284,50,9638,7,1919,1990,0.0,804.0

In [87]:
# Train Model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [88]:
# Predict values
y_pred = model.predict(X_test)

In [89]:
y_pred

array([203410.02104538, 230804.64745809, 120310.70269814, 132963.60280411,
       261141.03394636, 126641.85236757, 187715.24198543, 155485.11247574,
       123730.60996563, 141575.0045347 , 113539.00230337, 151895.64044173,
       116501.94445103, 245812.81892087, 197900.04631147, 192308.51350198,
       198423.58814636, 190788.15614376, 110641.31365023, 240475.89667505,
       173737.61268915, 200368.42897106, 193414.10647562, 175826.90787844,
       231204.98540039, 206783.56902955, 236977.08232927, 130883.09031896,
       197359.62756042, 233872.27894851, 121977.78843443, 211084.23904365,
       213230.13290579, 143425.69874791, 259543.53148147, 165150.82636716,
       158492.26006273, 198270.02509275, 232539.17410345,  72952.77268324,
       108796.13117056, 198749.46157092, 151586.69860448, 291114.74957126,
       144715.16067246,  84292.29556782, 130431.09246538, 157955.02900042,
       269898.08548492, 134391.03684759, 126037.52984625, 208073.50775859,
       117849.32787115, 209948.17038665, 195905.78153043, 263618.11909956,
       176153.16973401, 187581.46112763, 166446.45912532, 124106.86561754,
        84380.13259685, 182150.11824832, 221354.66925765, 255216.04935962,
       269778.06550214, 202995.78397515, 110894.29701395, 244744.00364893,
       190794.08538487, 179632.83269792, 102796.12692651, 141712.17803905,
       136875.47441165,  55492.61753458, 312416.34330895, 213214.51636113,
       227826.89437844, 217162.1199764 , 146115.00489476, 154554.07055358,
       168352.32264996,  92536.61956906, 146589.62566034, 120703.33381842,
       157588.48733451, 160718.2796903 , 221384.81715616, 210707.55323718,
       195902.61935217, 196848.10276868, 190396.4558823 , 138742.78768505,
       173272.08931906, 191417.88182152, 210259.74029127, 234664.44255853,
       171841.47563131, 177583.61909911, 246296.84836254, 177800.7987892 ,
       195826.46932242, 199812.24484367, 255765.84257989, 164300.01374421,
       205984.5123048 , 147533.12605552, 197048.78867401, 230192.67311896,
       194864.17894291, 162710.71727785,  56636.30377492, 172317.71679013,
       206427.15121924, 169501.76909544, 209223.85433648, 155150.48867339,
       176978.69265047, 149241.56675532, 103301.67332835, 351389.10281287,
       175315.95235915, 195905.78153043, 193575.50632077, 162204.13757981,
       214519.47489949, 148937.38340485, 200573.78572763, 113565.15410645,
       218472.2496484 , 157603.78237338, 193748.27686147, 273435.52007783,
       193403.54777898,  91469.24639448,  81762.89400456, 264600.08995897,
       264526.29529191, 162112.94647528, 249943.61882203, 312356.43957345,
       235284.32734965, 187673.01261043, 164025.58202531, 125497.11630739,
       169009.34786372, 144158.93480266, 168590.43308544, 241589.78624566,
       188635.64379615,  86820.10214978,  94128.57737681, 128133.03295265,
       240187.65764581, 154007.0364824 , 107945.06317133, 158205.57009788,
       170156.20252735, 161332.44680325, 137104.46514812, 161872.56381029,
       232042.24581353, 176003.73824359, 258803.24345834, 199553.57585746,
       114692.25784753, 193809.3999725 , 197062.45701441, 247983.68266882,
       287355.42734901, 151225.5024579 , 273303.60313596, 130803.11711164,
       111797.41975236, 142224.04147438, 247398.52673258,  77486.92335686,
       102084.89839348, 205334.26014676, 152974.78009495, 181803.71312484,
       213673.71630061,  99392.48178969, 163962.03365059, 150913.7926541 ,
       213981.06322757,  89512.69483833, 249519.11134533, 233021.92743903,
       236321.72875657, 122120.72652347, 138422.83344042, 134165.23784208,
       114983.25027512, 182218.4535421 , 229523.60718547, 182021.50880319,
       223338.83493566,  81737.15902517, 196315.52775658,  96965.14901647,
       266980.59121191, 194096.13992588, 144563.30632652, 233171.15589884,
       230260.7451029 , 144863.87745326, 206070.03712874, 160707.41860052,
       164220.22111715, 143347.05041029, 174215.15516219, 144747.16967318,
       138455.22950805, 179632.83269792, 229209.60168048, 253946.57004083,
       227161.77920013, 150911.94973298, 132277.11868979, 103051.45912567,
       159507.94422759, 233161.68167241, 204439.49825418, 102816.26560452,
       245564.24351573, 205532.8555718 ,  83695.07113527, 151181.26497813,
       184955.34876051,  99637.61722656, 122046.07079387, 172438.84710164,
       135644.74945368, 159795.85213714, 186819.50106632, 146912.54929559,
       225757.19429457, 193220.51411419, 203179.73546876, 166273.59421328,
       153733.20050343, 184578.88547072, 213213.38522635, 245897.89778822,
       163323.85954812, 161415.84712635, 153878.20274603, 200837.29738906,
       176703.55004049, 106056.44624403, 207022.32717882, 151739.04918874,
       144444.57267855,  90943.90798575, 161258.67251284, 169737.95704087,
       162173.91353946, 140763.23357454, 173788.99587805, 213428.40444977,
       281503.30995944, 190320.71963967, 153331.43962884, 226955.1145429 ,
       263744.77452295, 213318.99403849, 213338.78913231, 195319.89293298,
       137326.59213381, 161202.28100767, 290728.97422385, 213526.55312104,
       219987.89961066, 116464.54399432,  80105.93215665, 163122.34348873,
       202807.86570784, 273361.2506451 , 249585.68525968, 126739.31361652,
       207999.16669104, 137905.47874929, 196562.36569487, 164495.27690485,
       264532.24392616, 198742.15906509, 205361.08978856, 167559.30764419,
       254516.43727333, 192277.29900128, 106335.68535223, 158210.67856108,
       164321.41035702, 189783.11607271, 100936.69513005, 110909.13211405,
       115928.09269977, 165039.16586547, 193200.84655258, 162696.04602579,
       207455.36698664, 247847.87641822, 127942.71457673, 156872.35725772,
       191647.10713375, 168599.63101393, 168386.5159247 , 206767.31992716,
       183567.71194644, 157875.02685118, 152285.86168558, 223100.31502858,
       100256.26668769, 177355.34123675, 120652.98515532, 200016.05095443,
       221044.55859465, 185139.627496  , 266998.05178846,  54909.89111539,
       251678.81900819, 209302.71054764, 129816.09918135, 105825.24856845,
       206117.8049592 , 197948.85062919, 165780.87672375, 230483.49544017,
       164966.18959322, 149255.60788295, 176573.06840829, 164500.1131967 ,
       205824.46598221, 222248.22017315, 189388.18985946, 147326.38267338,
       132491.08073193, 144184.29702564,  84807.10892541, 246770.53596787,
       180953.53345186, 177552.22005112, 144554.5575903 , 227457.06617987,
       210216.75197477, 219395.41756769, 265677.64839154, 166715.60042964,
       186631.94034199, 182809.055434  , 183289.82912896, 296384.87689946,
       246883.83907017, 203333.28655096, 264196.93246481, 194758.59736045,
       143248.82608363, 124977.95236041, 189833.80831352, 277849.48940822,
       165827.13569805, 157015.62166719, 226759.04738169, 220376.99695446,
       140998.74337002, 230850.20205409, 189229.0594781 ,  92163.59830317,
       161740.17844562, 175949.83056362, 160072.77092157, 199931.28424678,
        92611.29594558, 190244.18677421, 167738.54143286, 119136.72016672,
       138319.22115296, 234055.18902852, 119012.31083892, 244325.93372128,
       183653.83684015, 196726.26301122, 188396.54613179, 175983.33408964,
       127252.06422395, 179843.64964528, 187767.5267976 , 101195.36817098,
       252677.97594933, 169238.99969025, 113881.87794035, 126047.88457565,
       169772.39553508, 272667.64046692, 163241.02524611, 253105.21931552,
       111667.50257668, 161729.42819929, 201498.99339745, 112802.23305563,
       192098.10889979, 294379.56303106, 106542.65813943, 164777.8966616 ,
       199334.1509644 , 151974.4292485 , 200552.21544836, 209374.29386057,
       230277.62778238, 233613.26036575, 176238.67784608, 241884.04746045,
        89241.74709577, 259443.72869036, 155200.73067056, 297597.86861401,
       162748.15454704, 225627.21315772, 241324.55052131, 155609.86365237,
       198212.43246272, 212453.00854809, 233678.61204983, 140143.51643631,
       189840.64473021, 141519.80648019, 241066.07320995, 163539.13074297,
       223815.88269891, 203924.2918698 , 134673.00751424, 180837.0053426 ,
       206818.7817407 , 179589.01645684, 204865.41770115, 206120.73032598,
       154724.28304016, 284725.98864381, 185377.78124484, 177113.51124902,
       200683.56796687, 276771.09702307, 184711.10137741, 160504.91982647,
       198046.51058606, 146328.64178901, 180685.87177266, 214149.68477711,
       150690.67607964, 168139.55491616, 135568.92427449, 120853.54393152,
       114880.36647152, 178073.93213845, 142335.65419953, 231238.35291363,
       224058.82080739, 236102.75918971, 216264.55250586, 104507.74193065,
       142192.51648692, 116841.31691854, 214066.44861946, 243185.12476541,
       208876.75831174, 299829.15964488, 164520.48657938, 230850.20205409,
       149101.92662702, 271414.45956539, 179922.43078812,  68349.17243395,
       164571.43803062, 126207.11888131, 199536.45332765, 280800.33823495,
       153555.53117044, 121164.59752458,  97155.07658543, 190645.85830146,
       163906.1478998 , 145032.62858293])

In [90]:
y_test

892     154500.0
1105    325000.0
413     115000.0
522     159000.0
1036    315500.0
          ...
1010    135000.0
390     119000.0
1409    215000.0
847     133500.0
1284    169000.0
Name: SalePrice, Length: 482, dtype: float64

In [91]:
# Evaluate 
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("r-squared:", r2)

n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1 - ((1-r2) * (n-1) / (n-p-1))
print("adjusted r^2:", adjusted_r2)

r-squared: 0.5526869948273663
adjusted r^2: 0.5460811065653232