In [61]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import f1_score, classification_report, accuracy_score, precision_score, recall_score

In [10]:
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

In [12]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [14]:
# df.isnull().sum()
df = df.fillna(df['bmi'].mean())

In [16]:
df_columns = ['gender',
 'ever_married',
 'work_type',
 'Residence_type',
 'smoking_status',]

le = LabelEncoder()

for col in df_columns:
    df[col] = le.fit_transform(df[col])

In [18]:
df.sample(10)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
2886,966,0,70.00,1,0,1,3,0,103.89,30.0,2,0
2323,22108,0,18.00,0,0,0,2,0,73.29,28.1,3,0
3998,62396,0,27.00,0,0,1,2,1,139.20,36.2,2,0
1006,6355,0,6.00,0,0,0,4,0,72.07,19.5,0,0
683,15274,0,2.00,0,0,0,4,0,79.89,31.6,0,0
3871,62986,0,60.00,1,0,1,2,0,78.26,41.7,1,0
2866,13375,1,76.00,0,0,1,2,1,192.39,31.0,2,0
3284,7979,0,26.00,0,0,0,2,0,69.77,23.2,2,0
848,50826,0,53.00,0,0,1,0,0,189.49,25.8,0,0
1499,45357,0,1.24,0,0,0,4,0,113.96,21.5,0,0

In [20]:
#  Covert numbers between 0 to 1

num_columns = ['id',
 'age',
 'avg_glucose_level',
 'bmi',]

scaler = MinMaxScaler()

for col in num_columns:
    df[col] = scaler.fit_transform(df[[col]])

In [22]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,0.123214,1,0.816895,0,1,1,2,1,0.801265,0.301260,1,1
1,0.708205,0,0.743652,0,0,1,3,0,0.679023,0.212981,2,1
2,0.426015,1,0.975586,0,1,1,2,0,0.234512,0.254296,2,1
3,0.824928,0,0.597168,0,0,1,2,1,0.536008,0.276060,3,1
4,0.021929,0,0.963379,1,0,1,3,0,0.549349,0.156930,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,0.249297,0,0.975586,1,0,1,2,1,0.132167,0.212981,2,0
5106,0.614850,0,0.987793,0,0,1,3,1,0.323516,0.340206,2,0
5107,0.269730,0,0.426270,0,0,1,3,0,0.128658,0.232532,2,0
5108,0.514278,1,0.621582,0,0,1,2,0,0.513203,0.175258,1,0
5109,0.612188,0,0.536133,0,0,1,0,1,0.139230,0.182131,0,0

In [73]:
# Split the data in to 2 parts 

X = df.drop(columns = ['stroke', 'id'], axis = 1)
y = df['stroke']

In [75]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [77]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42 )

In [79]:
X_train.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
802,1,0.963379,0,0,1,3,0,0.265534,0.208477,1
3927,0,0.755859,0,0,1,2,1,0.153264,0.297824,0
2337,0,0.255371,0,0,0,2,0,0.020312,0.268041,2
3910,1,0.377441,0,0,1,0,1,0.048841,0.230241,1
1886,0,0.377441,0,0,0,2,0,0.020820,0.109966,2

In [81]:
logistic_model = LogisticRegression(class_weight = 'balanced', max_iter=1000)

logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print("Accuracy Score : ", accuracy_score(y_test, y_pred))

Accuracy Score :  0.7495107632093934

In [87]:
y_prob = logistic_model.predict_proba(X_test)[:, 1]

for t in [0.5, 0.4, 0.3, 0.25, 0.2]:
    y_pred = (y_prob > t).astype(int)
    print("Threshold:", t)
    print(classification_report(y_test, y_pred))

Threshold: 0.5
              precision    recall  f1-score   support

           0       0.98      0.75      0.85       960
           1       0.16      0.76      0.27        62

    accuracy                           0.75      1022
   macro avg       0.57      0.75      0.56      1022
weighted avg       0.93      0.75      0.81      1022

Threshold: 0.4
              precision    recall  f1-score   support

           0       0.99      0.65      0.79       960
           1       0.14      0.90      0.25        62

    accuracy                           0.67      1022
   macro avg       0.57      0.78      0.52      1022
weighted avg       0.94      0.67      0.75      1022

Threshold: 0.3
              precision    recall  f1-score   support

           0       0.99      0.55      0.71       960
           1       0.12      0.94      0.21        62

    accuracy                           0.57      1022
   macro avg       0.56      0.74      0.46      1022
weighted avg       0.94      0.57      0.68      1022

Threshold: 0.25
              precision    recall  f1-score   support

           0       1.00      0.51      0.67       960
           1       0.11      0.97      0.20        62

    accuracy                           0.53      1022
   macro avg       0.55      0.74      0.44      1022
weighted avg       0.94      0.53      0.64      1022

Threshold: 0.2
              precision    recall  f1-score   support

           0       1.00      0.45      0.62       960
           1       0.10      0.97      0.18        62

    accuracy                           0.48      1022
   macro avg       0.55      0.71      0.40      1022
weighted avg       0.94      0.48      0.59      1022

In [89]:
print("Classification Report : ", classification_report(y_pred, y_test))
print(precision_score(y_pred, y_test))
print(recall_score(y_pred, y_test))

Classification Report :                precision    recall  f1-score   support

           0       0.45      1.00      0.62       433
           1       0.97      0.10      0.18       589

    accuracy                           0.48      1022
   macro avg       0.71      0.55      0.40      1022
weighted avg       0.75      0.48      0.37      1022

0.967741935483871
0.10186757215619695