In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes

In [7]:
df = load_diabetes(as_frame=True).frame

In [9]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [11]:
X = df.drop(columns = ['target'])
y = df['target']

In [13]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [15]:
# Split the data for training and testing 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, 
)

In [17]:
X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
384,0.034443,0.050680,-0.029918,0.004658,0.093372,0.086994,0.033914,-0.002592,0.024055,-0.038357
396,-0.085430,0.050680,-0.030996,-0.022885,-0.063487,-0.054236,0.019187,-0.039493,-0.096435,-0.034215
250,0.067136,-0.044642,0.056307,0.073515,-0.013953,-0.039205,-0.032356,-0.002592,0.075741,0.036201
50,0.034443,-0.044642,-0.007284,0.014987,-0.044223,-0.037326,-0.002903,-0.039493,-0.021395,0.007207
102,-0.092695,-0.044642,0.028284,-0.015999,0.036958,0.024991,0.056003,-0.039493,-0.005142,-0.001078
...,...,...,...,...,...,...,...,...,...,...
25,-0.067268,0.050680,-0.012673,-0.040099,-0.015328,0.004636,-0.058127,0.034309,0.019196,-0.034215
257,-0.027310,0.050680,-0.055785,0.025315,-0.007073,-0.023547,0.052322,-0.039493,-0.005142,-0.050783
231,0.009016,-0.044642,-0.030996,0.021872,0.008063,0.008707,0.004460,-0.002592,0.009434,0.011349
183,0.045341,0.050680,-0.035307,0.063187,-0.004321,-0.001627,-0.010266,-0.002592,0.015568,0.056912
392,-0.041840,0.050680,-0.029918,-0.002228,0.021822,0.036577,0.011824,-0.002592,-0.041176,0.065196

In [23]:
y_train

384     69.0
396     43.0
250    303.0
50     155.0
102    302.0
       ...
25     202.0
257     63.0
231    154.0
183    185.0
392    118.0
Name: target, Length: 353, dtype: float64

In [73]:
# Import the model from sklearn 
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth = 7, min_samples_leaf=20)
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=7, min_samples_leaf=20)

In [75]:
# accuracy score (how model performing and get correct output)
from sklearn.metrics import r2_score, mean_squared_error

y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

print("Train MSE :", mean_squared_error(y_train, y_pred_train))
print("Test  MSE :", mean_squared_error(y_test, y_pred_test))

print("Train R2  :", r2_score(y_train, y_pred_train))
print("Test  R2  :", r2_score(y_test, y_pred_test))

Train MSE : 2519.1859145757944
Test  MSE : 3554.8293161926795
Train R2  : 0.5747785632806548
Test  R2  : 0.4025359529431026

In [77]:
# for get tree structure plot 
from sklearn.tree import plot_tree

plt.figure(figsize=(18, 10))
plot_tree(
    model,
    feature_names=X.columns,
    filled=True
)

plt.tight_layout()
plt.show()

TypeError: 'module' object is not callable