In [62]:
import pandas as pd
import numpy as np
import seaborn as sns

In [182]:
df = pd.read_csv("adult.csv")

In [184]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [187]:
cat_cols = df.select_dtypes(include='object').columns

In [189]:
num_col = df.select_dtypes(include = 'int64').columns

In [191]:
for col in cat_cols:
    mode_value = df[col].mode()[0]
    df[col] = df[col].replace('?', mode_value)

In [193]:
df.sample(5)

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
4727,29,Self-emp-not-inc,110663,HS-grad,9,Separated,Craft-repair,Not-in-family,White,Male,0,0,35,United-States,<=50K
31541,34,Private,167781,HS-grad,9,Married-civ-spouse,Other-service,Husband,White,Male,0,0,50,United-States,<=50K
1074,63,State-gov,216871,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,1740,40,United-States,<=50K
27278,48,Private,265192,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K
16592,25,Private,86872,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K

In [195]:
cat_cols

Index(['workclass', 'education', 'marital.status', 'occupation',
       'relationship', 'race', 'sex', 'native.country', 'income'],
      dtype='object')

In [197]:
df['education'].unique()

array(['HS-grad', 'Some-college', '7th-8th', '10th', 'Doctorate',
       'Prof-school', 'Bachelors', 'Masters', '11th', 'Assoc-acdm',
       'Assoc-voc', '1st-4th', '5th-6th', '12th', '9th', 'Preschool'],
      dtype=object)

In [199]:
# covert data into number form 
from sklearn.preprocessing import LabelEncoder
cat_col = ['workclass', 'education', 'marital.status', 'occupation',
       'relationship', 'race', 'sex', 'native.country','income']
le = LabelEncoder()
for col in cat_col:
    df[col] = le.fit_transform(df[col])

In [201]:
X = df.drop(columns ='income', axis = 1)
y = df['income']

In [203]:
X

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,90,3,77053,11,9,6,9,1,4,0,0,4356,40,38
1,82,3,132870,11,9,6,3,1,4,0,0,4356,18,38
2,66,3,186061,15,10,6,9,4,2,0,0,4356,40,38
3,54,3,140359,5,4,0,6,4,4,0,0,3900,40,38
4,41,3,264663,15,10,5,9,3,4,0,0,3900,40,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,3,310152,15,10,4,10,1,4,1,0,0,40,38
32557,27,3,257302,7,12,2,12,5,4,0,0,0,38,38
32558,40,3,154374,11,9,2,6,0,4,1,0,0,40,38
32559,58,3,151910,11,9,6,0,4,4,0,0,0,40,38
32560,22,3,201490,11,9,4,0,3,4,1,0,0,20,38

In [205]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [215]:
# Covert the bigger values into 0 to 1 using minmax scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit(X_test)

In [217]:
# Cheacking the graph for the insight
import seaborn as sns
import matplotlib.pyplot as plt

# sns.scatterplot(data = df, y='hours.per.week', x='education.num', hue="income")
# plt.tight_layout()

In [219]:
# Import the Logistic Model to do Operation on the data 
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()

log_model.fit(X_train_scaled, y_train)

LogisticRegression()

array([[0.12328767, 0.42857143, 0.16905935, ..., 0.        , 0.24489796,
        0.95      ],
       [0.09589041, 0.42857143, 0.10947719, ..., 0.        , 0.34693878,
        0.95      ],
       [0.26027397, 0.42857143, 0.04402938, ..., 0.        , 0.39795918,
        0.95      ],
       ...,
       [0.52054795, 0.        , 0.15653744, ..., 0.43319559, 0.39795918,
        0.95      ],
       [0.32876712, 0.42857143, 0.09825105, ..., 0.        , 0.5       ,
        0.95      ],
       [0.06849315, 0.42857143, 0.104204  , ..., 0.        , 0.5       ,
        0.775     ]])