In [153]:
import pandas as pd
import numpy as np
import seaborn as sns

In [154]:
insurance = pd.read_csv("insurance.csv")

In [155]:
# Always check the important info and all that for the data

insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [156]:
X = insurance.drop(columns={'charges'})
y = insurance['charges']

In [157]:
X['sex'] = X['sex'].map({'female':1, 'male':0}) # How we convert the value in 0 and 1
X['smoker'] = X['smoker'].map({'yes':1, 'no':0}) # same work for the column
X['age_smoker'] = X['age']* X['smoker'] # for the new columns they will improve model
X['bmi_smoker'] = X['bmi']* X['smoker'] # I will also improve the mode accuracy

In [158]:
X.head()

   age  sex     bmi  children  smoker     region  age_smoker  bmi_smoker
0   19    1  27.900         0       1  southwest          19        27.9
1   18    0  33.770         1       0  southeast           0         0.0
2   28    0  33.000         3       0  southeast           0         0.0
3   33    0  22.705         0       0  northwest           0         0.0
4   32    0  28.880         0       0  northwest           0         0.0

In [159]:
X = pd.get_dummies(X, columns = ['region'], drop_first = True, dtype = int)

In [160]:
X.head()

,age,sex,bmi,children,smoker,age_smoker,bmi_smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,19,27.9,0,0,1
1,18,0,33.770,1,0,0,0.0,0,1,0
2,28,0,33.000,3,0,0,0.0,0,1,0
3,33,0,22.705,0,0,0,0.0,1,0,0
4,32,0,28.880,0,0,0,0.0,1,0,0

In [161]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size = 0.2, random_state = 42)

In [162]:
X_train.sample(10)

,age,sex,bmi,children,smoker,age_smoker,bmi_smoker,region_northwest,region_southeast,region_southwest
1070,37,0,37.070,1,1,37,37.070,0,1,0
176,38,0,27.835,2,0,0,0.000,1,0,0
1099,25,1,33.990,1,0,0,0.000,0,1,0
334,43,1,35.720,2,0,0,0.000,0,0,0
827,36,0,28.025,1,1,36,28.025,0,0,0
152,32,1,37.145,3,0,0,0.000,0,0,0
667,40,1,32.775,2,1,40,32.775,1,0,0
38,35,0,36.670,1,1,35,36.670,0,0,0
686,42,0,26.125,2,0,0,0.000,0,0,0
280,40,1,28.120,1,1,40,28.120,0,0,0

In [163]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [164]:
y_pred = model.predict(X_test)

In [165]:
y_pred

array([11244.92252985,  7419.09613036, 33108.56263345, 10825.70349972,
       28165.83120369,  6492.30055169,  2795.33432584, 14417.81581562,
        5687.02991028, 11674.71358693, 20657.59012262,  9146.41694187,
        5695.47866425, 51922.27364821, 52110.34418673, 46640.17211168,
       11685.28405314, 43258.65742309, 10134.76643993, 27544.17451838,
        5590.71503071,  9112.26016698,  1829.43896788,  4568.33364842,
       12451.66624573, 12838.44659475, 13233.15939348,  6449.57806469,
       11799.9498717 ,  1825.10642493,  9707.98622109, 12978.53418336,
        3236.11758774,  7025.39527005,  4125.34618621, 10091.32699237,
        3262.60876705,  9119.59871467, 26284.74334712, 37686.43163646,
        4634.27512745,  3702.06635756, 12658.69778308, 12849.08764218,
        6810.63583482, 12752.76878332,  4474.37122331,  5198.08817694,
       41615.58170738,  6338.51473147, 14310.53229154,  2272.59249937,
        9166.71958047,  2711.80386028, 11905.92268657, 12175.67773632,
        5854.02670898, 36417.51258036, 12666.40484692, 12587.08968911,
       13954.80184   ,  6697.59735566, 14380.51190716,  9820.68007771,
       12275.66910022,  5695.11524302, 20674.17954896, 12079.79217836,
        4836.41746496,  2803.98113331,  8657.45377405, 11653.22002719,
       10305.22670999,  8318.98122006,  9287.36175507,  7079.89367141,
        6599.96666125, 12589.61206771,  5965.23428348, 10486.28406414,
        2416.13118645, 32401.17997061,  6687.94605077, 38390.76594854,
       59888.23848679, 36869.71583868,  6399.6280826 , 11946.34954258,
       10199.91450251, 12286.85239922, 15979.12401001, 26964.44348463,
       28565.60464677,  7087.9528839 , 37711.5000273 ,  8578.13784222,
       27278.76502874,  2934.99654386, 20673.5996411 ,  8580.22549624,
        6271.45550473,  2324.4420131 ,  8080.09432489, 13065.60123388,
       13969.65965812,  2391.49615754,  9600.23991461, 20408.24052355,
        2616.86449   , 24348.95813123,  1884.50584216,  4726.43015539,
       14347.75285005, 33760.60119921, 11947.97548927,  2608.63879414,
       13807.42950826, 27593.62812417,  8287.20419042,  3883.67188912,
        8053.61946182,  9220.0433923 , 13355.11527796,  3519.65942579,
        6115.67973449,  9722.38868743,  9500.61913811, 11403.00435442,
       13236.16910043,  3380.0678798 ,  6007.77394554,  7770.62538709,
        7864.43932254, 10585.92213482,  7663.62574686, 12948.5621141 ,
        6842.53954437, 30796.56671824, 45796.54630475, 32392.72651821,
        7355.15737078, 12074.68818698,  4036.64983411, 12706.2564626 ,
        3576.24275758, 27017.89558934,  6978.62110504,  5484.30665671,
       12883.2142011 ,  6502.38296743, 46454.92734284,  3961.57761644,
        2049.45294977, 35254.45912732,  8623.31746763,  7093.89645001,
       14405.08268983, 10424.67015757, 30128.40467477, 36099.52832504,
       14799.31795222,  3324.40095477, 14492.11902441,  3993.77638469,
        4317.8473189 ,  9206.64009496, 48366.28428832, 37627.25511138,
       35034.91560344,  3930.88801511, 10522.09333045,  8120.69753646,
        8571.5603295 ,  5958.46589383,  3076.67716755, 26005.44970438,
       21273.22551244, 14133.17035249, 11959.10019049, 12802.21820997,
       34749.71044592,  4299.65760802, 10036.36499101,  6830.26102952,
        6920.55188464,  4331.1243504 ,  6139.48658495,  5192.77132798,
       10749.9726186 , 11841.72248145,  4407.58592884,  3299.40083485,
        4229.26446882, 38200.77728419, 13573.55410444, 11109.8773707 ,
        3299.21295857, 13687.32573036,  3241.27468978, 10409.58423   ,
        4630.39665392, 30111.48191952,  6194.43625498,  3292.99614351,
       21508.78271136, 19784.46069945, 10501.62381197,  4948.66372717,
        9918.72580223,  4200.32452939, 12954.11451051, 12944.56170696,
       11974.85136327, 22437.81419423,  8431.65118307,  6429.99845453,
        6720.4856199 , 14475.42792235, 13281.53510599,  7367.59701263,
        3590.61640066,  9191.11127137,  8545.61429898, 44268.31909526,
        3254.37633173, 29855.59614059,  2155.16236254,  2434.42931705,
       10964.46373453, 12586.98659778,  2750.90420905, 11119.6983409 ,
        5792.94492596, 27781.61366605, 11388.49309006, 10114.40397944,
        5207.49753653,  7953.49007788, 47972.86409635,  2951.06931675,
       14123.77113915, 36478.13595356,  4617.35694308,  4913.26265603,
        2323.98964141,  4284.9919505 ,  5589.10869331,  5733.83170209,
       13946.80966486,  2167.04904971,  2601.70074479,  8841.57096848,
        4628.05629528, 13414.26380011,  3448.4033976 ,  4697.39329159,
       12581.11378086,  4806.30842676, 10790.62358421,  8134.86511332,
        9833.47012818, 13811.52090887, 25818.71277593, 44213.45840034,
       13146.57694773,  8473.38764798, 60721.89031286, 11311.154888  ])

In [166]:
from sklearn.metrics import r2_score

r2 = r2_score(y_pred, y_test)

print("r2 score is ", r2)

r2 score is  0.8508509822647871

In [167]:
# The Best Prediction from the yeasterday and thsi is much good for learning progress 78% to 85% basically good]