In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import f1_score, classification_report, accuracy_score, precision_score, recall_score, r2_score

In [3]:
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

In [5]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [9]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [11]:
# df.isnull().sum()
df = df.fillna(df['bmi'].mean())

In [13]:
df_columns = ['gender',
 'ever_married',
 'work_type',
 'Residence_type',
 'smoking_status',]

le = LabelEncoder()

for col in df_columns:
    df[col] = le.fit_transform(df[col])

In [15]:
df.sample(10)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
2182,63401,0,71.00,0,0,1,3,0,249.29,30.300000,3,0
993,33401,1,64.00,0,0,1,2,0,84.27,24.600000,0,0
2227,13818,0,65.00,0,0,1,2,0,71.06,26.400000,2,0
3292,31766,1,18.00,0,0,0,2,0,102.58,30.800000,2,0
1390,3956,1,13.00,0,0,0,4,1,65.51,25.900000,0,0
518,21713,1,49.00,0,0,1,2,1,102.91,24.700000,0,0
3007,3135,0,73.00,0,0,0,3,0,69.35,28.893237,2,0
3440,18837,1,0.56,0,0,0,4,1,98.23,14.100000,0,0
4504,46048,1,60.00,0,0,1,0,0,203.27,29.700000,2,0
4958,63986,1,60.00,0,0,1,2,0,153.48,37.300000,2,0

In [17]:
#  Covert numbers between 0 to 1

num_columns = ['id',
 'age',
 'avg_glucose_level',
 'bmi',]

scaler = MinMaxScaler()

for col in num_columns:
    df[col] = scaler.fit_transform(df[[col]])

In [19]:
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,0.123214,1,0.816895,0,1,1,2,1,0.801265,0.301260,1,1
1,0.708205,0,0.743652,0,0,1,3,0,0.679023,0.212981,2,1
2,0.426015,1,0.975586,0,1,1,2,0,0.234512,0.254296,2,1
3,0.824928,0,0.597168,0,0,1,2,1,0.536008,0.276060,3,1
4,0.021929,0,0.963379,1,0,1,3,0,0.549349,0.156930,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,0.249297,0,0.975586,1,0,1,2,1,0.132167,0.212981,2,0
5106,0.614850,0,0.987793,0,0,1,3,1,0.323516,0.340206,2,0
5107,0.269730,0,0.426270,0,0,1,3,0,0.128658,0.232532,2,0
5108,0.514278,1,0.621582,0,0,1,2,0,0.513203,0.175258,1,0
5109,0.612188,0,0.536133,0,0,1,0,1,0.139230,0.182131,0,0

In [21]:
# Split the data in to 2 parts 

X = df.drop(columns = ['stroke', 'id'], axis = 1)
y = df['stroke']

In [23]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42 )

In [27]:
X_train.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
802,1,0.963379,0,0,1,3,0,0.265534,0.208477,1
3927,0,0.755859,0,0,1,2,1,0.153264,0.297824,0
2337,0,0.255371,0,0,0,2,0,0.020312,0.268041,2
3910,1,0.377441,0,0,1,0,1,0.048841,0.230241,1
1886,0,0.377441,0,0,0,2,0,0.020820,0.109966,2

In [29]:
logistic_model = LogisticRegression(class_weight = 'balanced', max_iter=1000)

logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print("Accuracy Score : ", accuracy_score(y_test, y_pred))

Accuracy Score :  0.7495107632093934

In [31]:
y_prob = logistic_model.predict_proba(X_test)[:, 1]

for t in [0.5, 0.4, 0.3, 0.25, 0.2]:
    y_pred = (y_prob > t).astype(int)
    print("Threshold:", t)
    print(classification_report(y_test, y_pred))

Threshold: 0.5
              precision    recall  f1-score   support

           0       0.98      0.75      0.85       960
           1       0.16      0.76      0.27        62

    accuracy                           0.75      1022
   macro avg       0.57      0.75      0.56      1022
weighted avg       0.93      0.75      0.81      1022

Threshold: 0.4
              precision    recall  f1-score   support

           0       0.99      0.65      0.79       960
           1       0.14      0.90      0.25        62

    accuracy                           0.67      1022
   macro avg       0.57      0.78      0.52      1022
weighted avg       0.94      0.67      0.75      1022

Threshold: 0.3
              precision    recall  f1-score   support

           0       0.99      0.55      0.71       960
           1       0.12      0.94      0.21        62

    accuracy                           0.57      1022
   macro avg       0.56      0.74      0.46      1022
weighted avg       0.94      0.57      0.68      1022

Threshold: 0.25
              precision    recall  f1-score   support

           0       1.00      0.51      0.67       960
           1       0.11      0.97      0.20        62

    accuracy                           0.53      1022
   macro avg       0.55      0.74      0.44      1022
weighted avg       0.94      0.53      0.64      1022

Threshold: 0.2
              precision    recall  f1-score   support

           0       1.00      0.45      0.62       960
           1       0.10      0.97      0.18        62

    accuracy                           0.48      1022
   macro avg       0.55      0.71      0.40      1022
weighted avg       0.94      0.48      0.59      1022

In [33]:
print("Classification Report : ", classification_report(y_pred, y_test))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print("r2_score is : ", r2_score(y_test, y_pred))

Classification Report :                precision    recall  f1-score   support

           0       0.45      1.00      0.62       433
           1       0.97      0.10      0.18       589

    accuracy                           0.48      1022
   macro avg       0.71      0.55      0.40      1022
weighted avg       0.75      0.48      0.37      1022

0.10186757215619695
0.967741935483871
r2_score is :  -8.117641129032261

In [35]:
from sklearn.linear_model import LassoCV

lassocv = LassoCV(
    cv=5,
    alphas=None,
    max_iter=1000,
    random_state=42
)

In [37]:
lassocv.fit(X_train, y_train)

LassoCV(cv=5, random_state=42)

In [39]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred = lassocv.predict(X_test)
print("Accuracy Score : ", r2_score(y_test, y_pred))
print("Accuracy Score : ", mean_squared_error(y_test, y_pred))

Accuracy Score :  0.09310171310957682
Accuracy Score :  0.051679667697846945